FROM jupyter/minimal-notebook
USER root
WORKDIR /workdir
COPY examples /workdir
RUN apt update && apt install --yes \
    make
RUN pip install \
    black[jupyter] \
    flake8 \
    geci-nerd \
    matplotlib \
    pandas
CMD ["bash", "-c", "umask 000 && jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''"]
