function ansInput = setInputDlg(ansInput)
dim = [15 3];

Title = 'Grupo de Ecología y Conservación de Islas, A.C.';

% static text
Prompt = cell(1,2);
Prompt{1,1} = ['The input files are generated by AgGPS TrimFlight are in Shapefile format and are named Track2D'];
Formats(1,1).type = 'text';
Formats(1,1).style = 'text';

Formats(1,1).size = [-1 0];
for k = 2:dim(2) % span the static text across the entire dialog
    Formats(1,k).type = 'none';
    Formats(1,k).limits = [0 1]; % extend from left
end

Prompt(end+1,:) = {'Input files','InputFiles'};
Formats(2,1).type = 'edit';
Formats(2,1).format = 'file';
Formats(2,1).limits = [0 10]; % multi-select files
Formats(2,1).size = 800;
Formats(2,1).items = {'*.txt','TracMap Data Logger';'log*.shp','TracMap GPS';'*Track2D*.shp','AgGPS TrimFlight';'*.*','All Files'};
for k = 2:dim(2) % span the file edit
    Formats(2,k).type = 'none';
    Formats(2,k).limits = [0 1]; % extend from left
end

%%%% SETTING DIALOG OPTIONS
Options.WindowStyle = 'modal';
Options.Resize = 'on';
Options.Interpreter = 'tex';


%%%% SETTING DEFAULT STRUCT
DefAns.InputFiles = ansInput.InputFiles;
[Answer,Cancelled] = inputsdlg(Prompt,Title,Formats,DefAns,Options);
ansInput.InputFiles=Answer.InputFiles;

%%%% SELECT DENSITY PROFILE
densityProfileFilename='.\DensityProfiles.mat';
load(densityProfileFilename)
n=length(ansInput.InputFiles);
S.DensityProfile={};
for i=1:n
    filename=ansInput.InputFiles{i};
    filename=filename(find(filename==filesep,1, 'last')+1:end);    
    %%% Ask about aperture diameter
    aperturePrompt={[filename char(10) 'Aperture diameter [mm]:']};
    numlines=1;
    defaultanswer={'90'};
    answer=inputdlg(aperturePrompt,filename,numlines,defaultanswer);
    ansInput.ApertureDiameter(i)= str2num(answer{1});
    %%% Ask about wind velocity
    windPrompt={[filename char(10) 'Enter wind speed [' densityProfile.units.windSpeed ']:'],'Enter wind direction ["coming from" in azimuth degrees]:'};
    numlines=1;
    defaultanswer={'0','0'};
    answer=inputdlg(windPrompt,filename,numlines,defaultanswer);
    ansInput.WindSpeed(i)     = str2num(answer{1});
    ansInput.WindDirection(i) = str2num(answer{2});
end
